name: Setup Workflow
description: Setup workflow for GitHub Actions

runs:
    using: composite
    steps:
        - uses: pnpm/action-setup@v4.0.0

        - name: Setup Node.js environment
          uses: actions/setup-node@v4
          with:
              node-version: 20
              registry-url: "https://registry.npmjs.org"
              cache: pnpm

        - name: Install dependencies
          run: pnpm install
          shell: bash
