packages:
  - apps/*
  - packages/*
  - website
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - lefthook
  - sharp
  - workerd

overrides:
  lru-cache: 11.5.2

