import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Carbon NextJS",
	description: "Generated by create carbon",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}