name: Renovate Changesets

on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - "packages/**"

jobs:
    renovate-changeset:
        runs-on: ubuntu-latest
        if: ${{ github.actor == 'renovate[bot]' }}
        steps:
            - uses: mscharley/dependency-changesets-action@v1.1.0
              with:
                  token: ${{ secrets.BUAPEBOT_SECRET }}
                  changeset-folder: ".changeset"
                  use-conventional-commits: false
                  author-name: "BuapeBot"
                  author-email: "119761697+buapebot@users.noreply.github.com"
