name: Publish Snapshots

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "packages/**"
            - "package.json"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'chore: update changelog and release')"
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/actions/setup

            - name: Publish Beta
              run: pnpm run publish:snapshot
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
